# USAGE: has_attached_file :photo, { :styles => { :thumb => "24x24#" }}.merge(PAPERCLIP_CONFIG)

local: &local
  url:  '/system/:attachment/:style/:id_partition/:basename.:extension'
  path: '/:rails_root/public/system/:attachment/:style/:id_partition/:basename.:extension'

s3: &s3
  storage: :s3
  s3_credentials: 
    access_key_id:     
    secret_access_key: 
  path:   ':attachment/:id/:style.:extension'
  bucket: 'vacationtrade.com'

development:
  <<: *local
  #<<: *s3

test:
  <<: *local

cucumber:
  <<: *local

production:
  <<: *s3
